name: deploy-web-nightly
on:
  workflow_dispatch:
env:
  # Remove after migrating to Cloud Run
  REEARTH_URL: test.reearth.dev
  GCS_DEST: gs://test.reearth.dev/

  GCP_REGION: us-central1

  IMAGE: reearth/reearth-classic-web:nightly
  IMAGE_GCP: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reearth/reearth-classic-web:nightly
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  # Remove after migrating to Cloud Run
  deploy_test_old:
    name: Deploy test env
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'reearth/reearth-classic'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: reearth/reearth-classic
          version: tags/nightly
          file: reearth-web_nightly.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: tar -xvf reearth-web_nightly.tar.gz
      - name: rsync
        run: gsutil -m -h "Cache-Control:no-store" rsync -x "^reearth_config\\.json$|^cesium_ion_token\\.txt$" -dr reearth-web/ $GCS_DEST

  deploy_test:
    name: Deploy test env
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'reearth/reearth-classic'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: docker push
        run: |
          docker pull $IMAGE
          docker tag $IMAGE $IMAGE_GCP
          docker push $IMAGE_GCP
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy reearth-classic-web \
            --image $IMAGE_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
