name: deploy-web-nightly
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy_test:
    name: Deploy test env
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'reearth/reearth-classic'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          service_account: ${{ secrets.GC_SA_EMAIL }}
          workload_identity_provider: ${{ secrets.GC_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
      - name: Configure docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: docker push
        run: |
          docker pull ${{ secrets.WEB_IMAGE }}
          docker tag ${{ secrets.WEB_IMAGE }} ${{ secrets.WEB_IMAGE_GC }}
          docker push ${{ secrets.WEB_IMAGE_GC }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy reearth-classic-web \
            --image ${{ secrets.WEB_IMAGE_GC }} \
            --region ${{ secrets.GC_REGION }} \
            --platform managed \
            --quiet
