name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Next version (NOTE: Switch the branch to "release"!)'
        type: choice
        default: minor
        options:
          - patch
          - minor
          - major
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Set up git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global pull.rebase false
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - id: changelog
        name: Generate CHANGELOG
        uses: reearth/changelog-action@main
        with:
          version: ${{ github.event.inputs.version }}
          repo: ${{ github.repository }}
          latest: CHANGELOG_latest.md
      - name: Upload latest CHANGELOG
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: changelog-${{ steps.changelog.outputs.version }}
          path: CHANGELOG_latest.md
      - name: Commit & push to release
        env:
          TAG: ${{ steps.changelog.outputs.version }}
        run: |
          rm CHANGELOG_latest.md
          git add CHANGELOG.md
          git commit -am "$TAG"
          git tag $TAG
          git push --atomic origin release $TAG
      - name: Commit & push to main
        run: git switch main && git cherry-pick release && git push
