name: renovate
on:
  push:
    branches:
      - renovate/*
jobs:
  renovate-go-sum-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@93a2c32f035d523d3faf771cf223c8f71c401f40 # v0.9.1
        with:
          git_user: ${{ github.actor }}
          git_email: ${{ github.actor }}@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_style: squash
          push: force
