name: renovate
on:
  push:
    branches:
      - renovate/*
jobs:
  renovate-go-sum-fix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@93a2c32f035d523d3faf771cf223c8f71c401f40 # v0.9.1
        with:
          git_user: ${{ github.actor }}
          git_email: ${{ github.actor }}@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_style: squash
          push: force
