name: renovate
on:
  push:
    branches:
      - renovate/*
jobs:
  renovate-go-sum-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@5966b2102f9cb296b5dd26989652f5a17b3bcb45 # v0.9.5
        with:
          git_user: ${{ github.actor }}
          git_email: ${{ github.actor }}@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_style: squash
          push: force
