name: Reviewer lottery
on:
  pull_request_target: # git-cascade:allow 
    paths:
        - web/**
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: uesteibar/reviewer-lottery@cc4b761dfe74c21bb26d04425a62704c021fefca # v3.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
